### ISSUE TITLE
[P. 111] Broker Bond Powers - typo and obtusely worded bond

### ISSUE THREAD

**Issue by tmprnc** [lenaleciel/KTB-Release-Typos-and-Errors#10]
On page 111, the Broker Bond power "Little Consequence" has the following text
> When you would take blame, personal fallout, or physical harm as a result of your actions, you have may another willing character nearby take the consequences instead of you after you learn what they are. If they do, they take **1 XP**.

The words "have" and "may" are inverted ("have may" instead of "may have"). Generally speaking, this phrase is obtusely worded and took me a few attempts to parse. I suggest the following:

> When you would take blame, personal fallout, or physical harm as a result of your actions; once you learn the consequences, another character may willingly suffer these consequences in your stead. If they do, they take **1 XP**.

**Comment by lenaleciel** [comment]
The may have have may inversion was fixed on 5/8, presumably that was deemed adequate.
