### ISSUE TITLE
[P. 134] - Typo - Emperor Core Power

### ISSUE THREAD

**Issue by thesjans** [lenaleciel/KTB-Release-Typos-and-Errors#11]
**The Problem:**
The Emperor's Core Active currently says:
"[...] which can be athe character it originated from. [...]"

**The Solution:**
"[...] which can be the character it originated from. [...]"

**The Location:**
On page 134, in Emperor Core Active.

**Comment by IFailAtGaming** [comment]
The armor piercing damage is also untyped, should likely be energy damage as it's described as a lightning bolt

**Comment by lenaleciel** [comment]
Both corrected on 5/8
