### ISSUE TITLE
[P. 96] - Incorrect Image - The Pathfinder's section has the image of the Broker

### ISSUE THREAD

**Issue by CCTuck** [lenaleciel/KTB-Release-Typos-and-Errors#12]
**The Problem:**
The Bond image for the Pathfinder bond (the "card") is incorrect; it currently displays the card of the Broker bond.

**The Solution:**
Replace the existing image with the correct one (the Pathfinder's card).

**The Location:**
On page 96 (Bonds section, Pathfinder)

**Comment by lenaleciel** [comment]
Fixed on 5/8.
