### ISSUE TITLE
[P.74] - Typo in Ludra's World

### ISSUE THREAD

**Issue by Dorsisdwarf** [lenaleciel/KTB-Release-Typos-and-Errors#13]
**The Problem:**
Text reads 
*"Baron Ludra decreed that this break-
down of the social order implied abdication, and
voided all claims of nobility with which they peti-
tioned his **cour.."***

**The Solution:**
_"Baron Ludra decreed that this break-
down of the social order implied abdication, and
voided all claims of nobility with which they peti-
tioned his **court**."_

**The Location:**
P.74, bottom right paragraph under Ludra's World: Paradise Above headline

**Comment by lenaleciel** [comment]
Fixed on 5/8.
