### ISSUE TITLE
[Page 96] - Typo - Harlequin Bond's Quirk List

### ISSUE THREAD

**Issue by RoboticHousewife** [lenaleciel/KTB-Release-Typos-and-Errors#15]
**The Problem:**
Third quirk listed for Bond of the Harlequin's "Quirks" starts with "Your" instead of "You".
See: "Your can swap your clothing’s coloration, material, fit, cut, and type completely when you enter any scene."
![KTB Typo- Page 96](https://user-images.githubusercontent.com/103589088/163215179-cdc7cf68-786f-42d2-a028-d42ec709f5bc.PNG)

**The Solution:**
"You can swap your clothing’s coloration, material, fit, cut, and type completely when you enter any scene."

**The Location:**
Page 96 in the pdf, listed as Page 92 on the bottom of the page.

**Comment by lenaleciel** [comment]
Fixed on 5/8.
