### ISSUE TITLE
[Pg 130] - White Witch Size icon shows Size 1

### ISSUE THREAD

**Issue by Squiddar** [lenaleciel/KTB-Release-Typos-and-Errors#16]
![Screenshot_20220413-103125_Drive](https://user-images.githubusercontent.com/37092543/163216624-652b26a5-94e8-4d71-b54e-5d500526443c.jpg)

The White Witch frame's Size icon in the top left of its page shows that it is Size 1, while its statblock shows that it is Size 2.

**Comment by lenaleciel** [comment]
Please use the template and stick the page number in the title next time.

**Comment by Squiddar** [comment]
> 

My bad, will do.

**Comment by Piezoelectric** [comment]
Possibly redundant with https://github.com/lenaleciel/KTB-Release-Typos-and-Errors/issues/21

**Comment by lenaleciel** [comment]
Closing for redundancy as noted.
