### ISSUE TITLE
[Pg 130] Unclear language on Fluid Burst frame trait.

### ISSUE THREAD

**Issue by CAWilliam** [lenaleciel/KTB-Release-Typos-and-Errors#18]
**The Problem:**
```When an allied character in Range 2 of this mech takes damage, it can reduce the damage by 1 and deal 1 AP kinetic damage to itself.```

At the moment the sentence could very easily be misconstrued as "Ally takes damage, ally reduces damage by 1, then takes 1 ap" which is clearly not the intended gameplay here. The allied character can easily be mistaken as the "it" being referenced in both the following instances.

Caveat, this is all based on my intuition that the read is supposed to be.
Ally takes damage.
White witch says "no" and the damage the ally takes is reduced by 1.
White witch takes 1 ap for making that decision

**The Solution:**
```When an allied character in Range 2 of this mech takes damage, the White Witch can reduce the damage taken by 1 and then deal 1 AP kinetic damage to itself.```

**The Location:**
Page 130, listed under the frame traits of the White Witch, bottom left.

**Comment by lenaleciel** [comment]
Fixed as of 5/8
