### ISSUE TITLE
[Page Number] - Two Size 1 Icons for all Frames

### ISSUE THREAD

**Issue by msprijatelj** [lenaleciel/KTB-Release-Typos-and-Errors#21]
**The Problem:**
All frames have 2 "Size 1 Icons" next to their titles.

**The Solution:**
Each frame should have a "Size" icon that matches their size (e.g. White Witch should be Size 2) and one or more "Role" icons to represent their role(s).

**The Location:**
- Pg. 130 (White Witch - Size 2 + Defender)
- Pg. 134 (Emperor - Size 1 + Support + Artillery)
- Pg. 140 (Orchis - Size 1 + Controller + Defender)
- Pg. 142 (Calendula - Size 1 + Controller)

**Screenshots**
![image](https://user-images.githubusercontent.com/44978587/163233034-bd721d28-9424-4bb1-b9b5-c37b0cd4025b.png)

**Comment by lenaleciel** [comment]
Fixed as of 5/8
