### ISSUE TITLE
[Credits] - Abbadon is credited inconsistently

### ISSUE THREAD

**Issue by JediDM99** [lenaleciel/KTB-Release-Typos-and-Errors#22]
**The Problem:**
Abbadon is credited as "Tom Bloom" as a writer, designer, and artist, but as "Tom Parkinson Morgan" as a cover artist.

**The Solution:**
Cover Art by
Tom Bloom
(I assume)

**The Location:**
In the credits page, the third page of the pdf, but 2 pages before actual page numbering starts.

**Comment by lenaleciel** [comment]
Fixed on 5/8
