### ISSUE TITLE
[Emperor] - Mech stats not showing up

### ISSUE THREAD

**Issue by Ministree** [lenaleciel/KTB-Release-Typos-and-Errors#24]
**The Problem:**
When selecting the emperor frame to edit, there are no mech stats shown. 
![image](https://user-images.githubusercontent.com/77934765/163247030-4f1490eb-e669-49b2-b8cb-a2072a6fcd56.png)

**The Solution:**
There should be a mech stat block underneath the mech frame traits like this
![image](https://user-images.githubusercontent.com/77934765/163247169-3b1721bd-12f1-47d1-a543-203f052d7542.png)

**The Location:**
KTB LCP in Emperor mech hangar

**Comment by lenaleciel** [comment]
Restructuring the tracker to direct LCP related concerns to the Comp/Con team
