### ISSUE TITLE
[Error popup] - When selecting Emperor for mech hanger, error message pops up

### ISSUE THREAD

**Issue by Ministree** [lenaleciel/KTB-Release-Typos-and-Errors#25]
**The Problem:**
Every time the emperor is selected and/or hovered over, the error message "Error: Cannot read properties of null (reading 'toString')" pop up and travel to the top of the screen before it appears again at the bottom right

**The Solution:**
The error message should not pop up

**The Location:**
Mech hanger when selecting the emperor frame

**Comment by lenaleciel** [comment]
Restructuring the tracker to direct LCP related concerns to the Comp/Con team
