### ISSUE TITLE
[P.121] - Placeholder page reference - Reference to faction operations is a placeholder page number

### ISSUE THREAD

**Issue by Dammitpants** [lenaleciel/KTB-Release-Typos-and-Errors#26]
**The Problem:**
Currently reads "Factions can also attempt to acquire new assets to increase their ratings (see the faction operations on p.
XX) or, alternatively, PCs can undertake missions to obtain assets on behalf of factions."

**The Solution:**
I don't see another header in the document for "faction operations", but the "XX" should be updated to reflect the correct page number

**The Location:**
Page 121 under the "Gaining New Assets" header.

**Comment by lenaleciel** [comment]
redundant with #28
