### ISSUE TITLE
[120] - describing faction ratings -  Factions that are poor at something have a rating or 0

### ISSUE THREAD

**Issue by Polish-vamp** [lenaleciel/KTB-Release-Typos-and-Errors#27]
**The Problem**
It says "have a rating or 0"

**The Solution:**
it should be "have a rating _of_ 0
**The Location:**
Pg 120, 2nd paragraph, right after the bullet points

<img width="233" alt="image" src="https://user-images.githubusercontent.com/103609046/163277761-b2d0b609-865d-45ae-b8e5-bced9d523612.png">

**Comment by lenaleciel** [comment]
fixed on 5/8
