### ISSUE TITLE
[53, 86, 121] - XX placeholders

### ISSUE THREAD

**Issue by phenomen** [lenaleciel/KTB-Release-Typos-and-Errors#28]
**The Problem:**
XX placeholders.

**The Solution:**
Add the final text / page numbers instead of placeholders.

**The Location:**
p. 53: The House of Stone’s primary color is XX.
p. 86: ...except when determining the effect of actions (p. XX)
p. 121: ...to increase their ratings (see the faction operations on p. XX)

**Comment by lenaleciel** [comment]
Fixed on 5/8
