### ISSUE TITLE
[P.117-118] - Faction Reserves Mention Saves instead of Checks

### ISSUE THREAD

**Issue by Icosacube** [lenaleciel/KTB-Release-Typos-and-Errors#30]
**The Problem:**
The Tactical Faction Aid (Mech Combat) entry, Take the Shot (p.117), and the Tactical Faction Interference (Mech Combat) entries, Bombardment and Jamming Wave, mention saves that do not originate from a specific character.

![image](https://user-images.githubusercontent.com/54576221/163306525-0aa0abc6-7bf2-46ca-9f7e-58c6f45685fb.png)
![image](https://user-images.githubusercontent.com/54576221/163306548-572cde6f-2e61-42b7-b792-9aa284639d4f.png)
![image](https://user-images.githubusercontent.com/54576221/163306573-892cfa9f-c452-4b70-b3dd-6aa7dd277f02.png)

**The Solution:**
These should probably be corrected to say "check" instead. For example:
> ...and must succeed on an AGILITY **check** or...

**The Location:**
These items are located in the Tectical Faction Aid/Interference (Mech Combat) tables on pages 117-118.

**Comment by lenaleciel** [comment]
fixed on 5/8
