### ISSUE TITLE
[137] - Missing period in Ayah of the Syzygy description 

### ISSUE THREAD

**Issue by Piezoelectric** [lenaleciel/KTB-Release-Typos-and-Errors#31]
**The Problem:**

There's a missing period in between 

 "within SENSORS and line of sight The first time each turn"

**The Solution:**

Add the period so it reads "within SENSORS and line of sight. The first time each turn..."

**The Location:**

Page 137, Ayah of the Syzygy menchanical description

**Comment by lenaleciel** [comment]
Fixed on 5/8
