### ISSUE TITLE
[140] - Orchis Core Power Capitalization Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [lenaleciel/KTB-Release-Typos-and-Errors#33]
**The Problem:**
This may or may not be intended, but the Orchis core active statblock reads HELION is in all caps, and while Lancer is no stranger to randomly capitalizing words for aesthetic effect, in this particular case I'm less certain it's intended.

**The Solution:**
The name for this core active should most likely be "Helion," not in all capital letters. Specifically this is referring to its use in the green statblock box, not the black text version.

**The Location:**
Page 140

**Comment by lenaleciel** [comment]
Fixed on 5/8
