### ISSUE TITLE
[72] - "[...] company of for the House" - Blurb on the Graveborn has two prepositions

### ISSUE THREAD

**Issue by aronmorris** [lenaleciel/KTB-Release-Typos-and-Errors#35]
**The Problem:**
The Graveborn blurb in House Companies, on page 72, has the line "as such, they are technically the banner company of for the House"

**The Solution:**
Drop one of the two prepositions. Keep "of" if the Graveborn are the official capacity banner company. Keep "for" if the Graveborn are the de facto banner company.

**The Location:**
72

**Comment by lenaleciel** [comment]
fixed on 5/8
