### ISSUE TITLE
[71] - Mixed quotes - A quote line within the First Chapter blurb opens with a double and closes with two singles

### ISSUE THREAD

**Issue by aronmorris** [lenaleciel/KTB-Release-Typos-and-Errors#36]
**The Problem:**
 just as “proven on Ras Shamra'' is the mark of quality for Armory mechs

You can note that the quote "proven on Ras Shamra" starts with a " character and ends with two ' characters.

**The Solution:**
Replace the two single quotes with a double quote. 50% character savings.

**The Location:**
71

**Comment by lenaleciel** [comment]
fixed on 5/8
