### ISSUE TITLE
[P. 132] Inconsistent Margins Between White Witch System Text Boxes

### ISSUE THREAD

**Issue by Icosacube** [lenaleciel/KTB-Release-Typos-and-Errors#4]
![image](https://user-images.githubusercontent.com/54576221/163209657-b935f688-01d5-4e63-92a0-9435865b9e54.png)

The margins between these two text boxes are inconsistent.

They should be lined up flush with each other.

**Comment by lenaleciel** [comment]
Camus Razor is a White Witch system, not an Emperor one. Also might be intentional, due to the reaction being given by the Quick Action.

**Comment by lenaleciel** [comment]
Checked, is intentional as in #5
