### ISSUE TITLE
[49] - "most densely populated worlds (per capita)" - incorrect qualifier

### ISSUE THREAD

**Issue by inquisitivecrystal** [lenaleciel/KTB-Release-Typos-and-Errors#40]
**The Problem:**
The text says that Arrudye is "one of the most densely populated worlds (per capita) in the galaxy". The "per capita" qualifier doesn't make sense. 

Population density means "people per unit area". "Per capita" means "per person". Thus, "one of the most densely populated worlds (per capita) in the galaxy" means "one of the worlds with the most people per unit of area (per person) in the galaxy". Since "person" is already part of the concept of population density, the "(per capita)" qualifier isn't coherent. Apologies if this is over-explaining.

**The Solution:**
Change the sentence to read "On Arrudye, the moon of Karrakis, the House of Remembrance oversees one of the most densely populated worlds in the galaxy.", thereby removing the text "(per capita)".

**The Location:**
The first sentence of the first paragraph on page 49, which currently and incorrectly reads "On Arrudye, the moon of Karrakis, the House of Remembrance oversees one of the most densely populated worlds (per capita) in the galaxy."

**Comment by lenaleciel** [comment]
Per capita removed on 5/8
