### ISSUE TITLE
[134] - Spacing Typo in Xerxes Apex Keywords

### ISSUE THREAD

**Issue by KaiTave** [lenaleciel/KTB-Release-Typos-and-Errors#42]
**The Problem:**
In the text box for the Emperor core active ability Xerxes Apex, there isn't a space between the comma and the word "Protocol" in the keywords, reading "Active (1CP),Protocol"

**The Solution:**
It's a minor typo, but if a pass is being done, all that needs incorporation here is a space after the comma.

**The Location:**
Page 134

**Comment by lenaleciel** [comment]
Fixed on 5/8
