### ISSUE TITLE
 [132] - Camus's Razor Developer Input/Clarification Request

### ISSUE THREAD

**Issue by KaiTave** [lenaleciel/KTB-Release-Typos-and-Errors#43]
The Problem:
Currently, the White Witch's Camus's Razor system seems to behave somewhat unusually by Lancer system standards in that it costs a Quick Action to activate, but then lasts for the duration of the scene without any further upkeep or ongoing penalty.

Generally speaking, in Lancer there are two sorts of systems, ones which you activate and have a limited duration or prime a charge that's expended on use (such as Mimic Mesh or Stasis Bolt) or that remain active indefinitely but which have some ongoing impairment (such as an Assault Cannon being spun up or a Hardlight Defense System). However Camus's Razor, as written, seems to only require a single-time activation after which it simply lasts for the remainder of the scene. 

Thus there seems to be no reason to not simply activate it at the start of every fight, which means it has no real opportunity cost or consideration to its use, just a single Quick Action tax at the start of each fight. I'm creating this ticket to ask whether this is intentional or not? The earlier, playtest version of this system, lasted until the start of your next turn, meaning it was more like Mimic Mesh. Should it have a limited duration, or create a charge like Stasis Bolt which is expended upon use and can't be stacked? Should it last indefinitely but have some debuff like Slow when active? This seems like something to bring to Tom's attention for clarification of intent.

The Location:
Page 132

**Comment by lenaleciel** [comment]
Explicitly reworded to make it clear that it lasts until the end of the scene or used.
