### ISSUE TITLE
[93] - Harlequin Bond Power Typo

### ISSUE THREAD

**Issue by KaiTave** [lenaleciel/KTB-Release-Typos-and-Errors#44]
**The Problem:**
The Harlequin bond power EXUENT is, I feel reasonably certain, supposed to actually be spelled **EXEUNT** as in the stage direction for someone making an exit.

**The Solution:**
As noted above, I believe that it should be EXEUNT instead.

**The Location:**
Page 93

**Comment by lenaleciel** [comment]
Fixed on 5/8
