### ISSUE TITLE
[P. 136] - Formating - Bold Text missing

### ISSUE THREAD

**Issue by Ferrin33** [lenaleciel/KTB-Release-Typos-and-Errors#6]
**The Problem:**
Bold text missing from "The Imperial Eye" system.

**The Solution:**
Bolded in this order:
Sensors
Range 3
2 AP energy damage
Engineering
Prone
Shredded
Range 3.

**The Location:**
KTB P.136 "The Imperial Eye"

**Comment by lenaleciel** [comment]
Fixed as of 5/8
