### ISSUE TITLE
[P. 89] Burdens Missing Image

### ISSUE THREAD

**Issue by Icosacube** [lenaleciel/KTB-Release-Typos-and-Errors#7]
![image](https://user-images.githubusercontent.com/54576221/163210446-11604057-84c1-4de9-8f90-163553f99891.png)
As noted by others, the Burdens section lists `[example burdens image]` instead of the image proper.

Instead of this text, the image should be incorporated.

**Comment by lenaleciel** [comment]
Fixed as of 5/8
