### ISSUE TITLE
[P. 90] - Clocks - wrong word termination

### ISSUE THREAD

**Issue by tmprnc** [lenaleciel/KTB-Release-Typos-and-Errors#8]
On page 90, when describing the clocks system, the sentence "give the clock a nam**ed** based on" is used, making "name" a past participle instead of a noun as it should be.

![1649857084](https://user-images.githubusercontent.com/3785923/163211084-15ac8dd7-4e02-4fc9-ae56-e31eb1b861c4.png)

**Comment by lenaleciel** [comment]
Fixed on 5/8
