### ISSUE TITLE
[P. 55] - House of Water canton-sigil inconsistency

### ISSUE THREAD

**Issue by Dorsisdwarf** [lenaleciel/KTB-Release-Typos-and-Errors#9]
**The Problem:**
The House of Water's Canton-Sigil is listed as depicting six blades of grass, but their sigil artwork depicts three-bladed grass

**The Solution:**
Either one of these ought to be changed to make them correct

**The Location:**
Page 55, top left / "color and sign"

**Comment by lenaleciel** [comment]
Fixed on 5/8
